c1=int(input("Price of item 1 : "))
c2=int(input("Price of item 2 : "))
c3=int(input("Price of item 3 : "))
print("----------------------------------------------------------------------------------------------------------------")
print("----------------------------------------------------------------------------------------------------------------")
print("Discount Details")
d=int(input("Provide discount(in percentage) for the first saver combo  : "))
e=int(input("Provide discount(in percentage) for the second saver combo  : "))
f=int(input("Provide discount(in percentage) for the third saver combo  : "))
c4=(c1+c2)*(1-(d/100))
c5=(c1+c3)*(1-(e/100))
c6=(c3+c2)*(1-(f/100))
c7=(c1+c2+c3)*(1-(28/100))
print("----------------------------------------------------------------------------------------------------------------")
print("----------------------------------------------------------------------------------------------------------------")
def ghf():
    g=int(input("Provide your 10 digit contact number : "))
    count=0
    while g!=0:
        g=g%10
        count=count+1
    if g<0:
        ghf()
    if count != 10:
        ghf()
ghf()
print("")
print("----------------------------------------------------------------------------------------------------------------")
print("----------------------------------------------------------------------------------------------------------------")
print("The resulting catalogue is : ")
print("----------------------------------------------------------------------------------------------------------------")
print("")
print("----------------------------------------------------------------------------------------------------------------")
print("Delhi Days")
print("Shop no. 18A - Select City Walk mall,Saket")
print("New Delhi - 110017")
print("Special offers for deppresed IIITD student....Avail Now")
print("----------------------------------------------------------------------------------------------------------------")
print("----------------------------------------------------------------------------------------------------------------")
print("# What you get here #                         # Discounts we Offer #                         # Prices per pack #")
print("1.Item-1                                                NA                                          Rs.",c1)
print("2.Item-2                                                NA                                          Rs.",c2)
print("3.Item-3                                                NA                                          Rs.",c3)
print("4.ComboPack-A                                          ",d,"%                                        Rs.",c4)
print("5.ComboPack-B                                          ",e,"%                                        Rs.",c5)
print("6.ComboPack-C                                          ",f,"%                                        Rs.",c6)
print("7.SuperSaver                                             28%                                         Rs.",c7)
print("Hey! we even offer Home Delivery.....Home delivery is free on your first order.....Order Now.....Contact us ASAP")
print("Home Delivery Charges -> Rs.50 per km for order less than 500 <-> Free for order above Rs.500")
print("----------------------------------------------------------------------------------------------------------------")
print("Contact us")
print("EMAIL- xyz@iiitd.ac.in")
print("Call at : 7892739536")
print("----------------------------------------------------------------------------------------------------------------")